<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="castor_visual" params="name">
    <visual>
      <geometry>
        <cylinder radius="${CASTOR_RADIUS}" length="${CASTOR_THICKNESS}"/>
      </geometry>
      <material name="${name}_castor_color">
        <color rgba="${CASTOR_COLOR}"/>
      </material>
    </visual>
  </xacro:macro>
  <xacro:macro name="castor_joint" params="name translation_x translation_y">
    <joint name="${name}_castor_joint" type="continuous">
      <origin 
        xyz="
          ${translation_x} 
          ${translation_y} 
          ${CASTOR_RADIUS-(BASE_HEIGHT/2+BASE_ELEVATION)+0.0001}
        "
        rpy="${-PI/2} 0 0"
      />
      <parent link="base_link"/>
      <child link="${name}_castor"/>
      <axis xyz="0.0 0.0 1.0"/>
    </joint>
  </xacro:macro>
  <xacro:macro name="castor_graphics" params="name translation_x translation_y">
    <link name="${name}_castor">
      <xacro:castor_visual name="${name}"/>
    </link>
    <xacro:castor_joint 
      name="${name}"
      translation_x="${translation_x} "
      translation_y="${translation_y} "
    />
  </xacro:macro>
  
  <xacro:macro name="castor_set_graphics" params="">
    <xacro:castor_graphics 
      name="left_front" 
      translation_x="${CASTOR_SEPARATION_X/2}" 
      translation_y="${CASTOR_SEPARATION_Y/2}"
    />
    <xacro:castor_graphics 
      name="right_front" 
      translation_x="${CASTOR_SEPARATION_X/2}" 
      translation_y="${-CASTOR_SEPARATION_Y/2}"
    />
    <xacro:castor_graphics 
      name="left_rear"
      translation_x="${-CASTOR_SEPARATION_X/2}" 
      translation_y="${CASTOR_SEPARATION_Y/2}"
    />
    <xacro:castor_graphics 
      name="right_rear" 
      translation_x="${-CASTOR_SEPARATION_X/2}" 
      translation_y="${-CASTOR_SEPARATION_Y/2}"
    />    
  </xacro:macro>
  
</robot>
